### PR TITLE
[READY-TO-REVIEW] Updating the OWH Diagrams

### PR DESCRIPTION
**Pull request by jarusso**

### CODE REVIEW

**Comment by jarusso** [comment]
@miguelestrada please review and merge

**Comment by miguelestrada** [comment]
image

@jarusso 
Perhaps we can indicate between steps 3 and 4 that the developer must click the button "Enable" in their webhook definition in the DX for step 4 to take place?

**Comment by jarusso** [comment]
Ok, I can add that in the "step definition" bit

**Comment by jarusso** [comment]
@miguelestrada updated, please review and merge

**Pull request merged**
