### PR TITLE
[READY FOR REVIEW] Broken link in photo service reference doc

### PR DESCRIPTION
**Pull request by miguelestrada**
Fix broken link in doc

### CODE REVIEW

**Comment by miguelestrada** [comment]
Tested in local build

**Comment by miguelestrada** [comment]
@jarusso

**Comment by jarusso** [comment]
@miguelestrada is this ready to merge?

**Comment by miguelestrada** [comment]
@jarusso merging this.... 
In reviewing, what about making a reference to this photo API in the people intro document?

**Pull request merged**
