### PR TITLE
[Ready for Review] Tip text

### PR DESCRIPTION
**Pull request by swhitehe**
wrap tip text in tag so it can be styled according to https://github.ibm.com/toscana/planning/issues/31898

### CODE REVIEW

**Comment by swhitehe** [comment]
@jarusso @miguelestrada please review

**Comment by miguelestrada** [comment]
@swhitehe did you do a build on this to showcase rendering?

**Comment by swhitehe** [comment]
@miguelestrada yes, I built locally to ensure the text changed still renders correctly

**Comment by jarusso** [comment]
@swhitehe any chance I can see that working?

**Comment by swhitehe** [comment]
screen shot 2018-04-30 at 1 05 05 pm
screen shot 2018-04-30 at 1 08 00 pm

@jarusso these are the two instances of 'tip' text changing. The only difference visually is the text 'TIP:' becoming bold. The css class is added so that I can style the text in a separate PR within the developer-experience repo, with the end goal being the design in the issue linked to in my original comment above.

**Pull request merged**
