### PR TITLE
[READY-TO-REVIEW]Add in system diagrams

### PR DESCRIPTION
**Pull request by jarusso**

### CODE REVIEW

**Comment by jarusso** [comment]
@miguelestrada @nivekselig  can you review?

**Comment by ghost** [comment]
LGTM

**Comment by miguelestrada** [comment]
Summary of our review:

1.  These are more focused on annotations + moments.... Need to move to annotation section or make them into a broader more inclusive overview
2.  Fonts are too small / github UI scaling pictures?  Break up into separate images perhaps
3.  Messages are posted to conversations which are inside a space (vs to a space)
4.  Watson is also utilize to compute spaces important to you

**Review by miguelestrada — CHANGES_REQUESTED** [review]
Content good in general.  Just need a few changes as discussed:
1. Font size of diagrams too small
2. Diagram for posting follow on msgs with annotations missing messages
3. Purple arrow head too small
4. Group of users too far on right in last card.

**Comment by jarusso** [comment]
@miguelestrada ok I've made the changes requested

**Review by miguelestrada — APPROVED** [review]

**Pull request merged**
