### PR TITLE
Pagination into DX

### PR DESCRIPTION
**Pull request by jarusso**

### CODE REVIEW

**Comment by jarusso** [comment]
@miguelestrada please review and merge

**Comment by miguelestrada** [comment]
@jarusso how about incorporating this right into the existing graphQL API doc?  It is something that applies to the patterns of using the API (how to handle result sets...)

**Comment by jarusso** [comment]
I added it separate so there is a visible place to find it since it applies to every other Guide section (that is about a collection)

**Comment by miguelestrada** [comment]
@jarusso can you address conflicts?

**Comment by miguelestrada** [comment]
Still think it falls nicely into the existing graphQL API doc, but at least lets get this out there

**Pull request merged**
