### PR TITLE
Add filtered spaces query page

### PR DESCRIPTION
**Pull request by jaumb**

### CODE REVIEW

**Comment by jaumb** [comment]
@miguelestrada I opened this PR to follow up the addition of filters to the spaces query. What's the typical review process for this repository? Is there a way to view the developer docs with this change before it's merged?

**Comment by miguelestrada** [comment]
@jaumb in your case, you can build DX local per the DX project readme.

**Comment by miguelestrada** [comment]
@jaumb perhaps expand on what these two params do a little more and the implied meaning?

@jarusso should the try-it now be now done with a specific button style?

**Comment by miguelestrada** [comment]
@jaumb @jarusso bump

**Comment by jaumb** [comment]
Closing as non-essential work

**Pull request closed without merging**
