### PR TITLE
[Ready to Review] add class for try it now button styling

### PR DESCRIPTION
**Pull request by swhitehe**
Links to 'Try it now' get a css class added so they can be styled as a button according to https://github.ibm.com/toscana/planning/issues/31898

Screenshots below include yet to be merged styling, without styling the 'Try it now' links just look as they do today:
screen shot 2018-05-30 at 11 50 54 am

screen shot 2018-05-30 at 11 51 04 am

screen shot 2018-05-30 at 11 51 20 am

### CODE REVIEW

**Comment by swhitehe** [comment]
@miguelestrada @jarusso please review

**Comment by jarusso** [comment]
@swhitehe 
this looks fine to me - do we need to hold this PR merge until https://github.ibm.com/toscana/developer-experience/pull/336 is merged? 

Also I assume you gave this the once over for mobile rendering 

@miguelestrada FYI

**Comment by swhitehe** [comment]
@jarusso this is fine to merge before the styling. The order in this case doesn't matter - either way with one merged everything will look the same as it does now. This one merged first just means "try it now" links with a class added but that class has no styling; the styling merged first just means styles sitting in the css files but not yet applied to anything.

**Comment by AlanGreene** [comment]
@jarusso @miguelestrada ok to merge?

**Pull request merged**
