### PR TITLE
Added documentation for includeSoftDeleted param and softDeleted field

### PR DESCRIPTION
**Pull request by roy713**
# Changes include:

- Added includeSoftDeleted parameter in the messages collection query
- Added softDeleted property to the message, along with documentation

@jarusso @miguelestrada - Would you mind reviewing these changes?

**This feature is currently enabled as `EXPERIMENTAL` but will be promoted to published in the feature enablement process. I just want to get ahead of this and gather feedback sooner rather than later.**

Thanks!

### CODE REVIEW

**Review by miguelestrada — APPROVED** [review]

**Comment by miguelestrada** [comment]
@roy713 

>This feature is currently enabled as EXPERIMENTAL but will be promoted to published in the feature enablement process.

From EXPERIMENTAL it should go to BETA.  The WW client can have a published end user feature....the API can still be in EXPERIMENTAL or BETA phase though as it is independent from the "feature" in WW.

**Review by miguelestrada — CHANGES_REQUESTED** [review]
@roy713 can there be a reference to the fact that these params require the EXPERIMENTAL value in x-graphql-view header?  I think you did this already in another PR.

**Comment by roy713** [comment]
@miguelestrada - I believe I tried to look for an example of this in the docs but couldn't find one since the `EXPERIMENTAL` components here are part of a published API. Do you think I can just add it in the description? Something like:

- For the `messages` call:

The messages of this conversation provided as a MessageCollection. The `includeSoftDeleted` parameter requires the `EXPERIMENTAL` value in `x-graphql-view header`.

- For the `Message` object:

Indicates whether this message is soft-deleted. Soft-deleted messages will return null content and empty annotations. This requires the `EXPERIMENTAL` value in `x-graphql-view header`.

**Comment by roy713** [comment]
@miguelestrada - I added the requested changes. Would you mind reviewing/merging these changes? Thanks!

**Review by miguelestrada — APPROVED** [review]

**Pull request merged**
